server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate      /etc/nginx/ssl/ssl.crt;
    ssl_certificate_key  /etc/nginx/ssl/ssl.key;
    ssl_protocols        TLSv1.2 TLSv1.3;

    return 301 https://127.0.0.1$request_uri;
}

server {
	# Listen on HTTPS port and use SSL on both IPv4 and IPv6
	listen			443 ssl default_server;
	listen			[::]:443 ssl default_server;

	server_name		gamepad;

	# Specify the SSL/TLS protocols allowed for HTTPS connections.
	ssl_protocols			TLSv1.2 TLSv1.3;

	# Specify the SSL key and certificate for HTTPS
	ssl_certificate			/etc/nginx/ssl/ssl.crt;
	ssl_certificate_key		/etc/nginx/ssl/ssl.key;

	add_header X-XSS-Protection "1; mode=block";
	add_header X-Content-Type-Options "nosniff";
	proxy_cookie_path / "/; HttpOnly; Secure; SameSite=Strict";

	# Define the root directory for serving web content.
	root		/www;
	# Specify the default index files for directory listings.
	index		index.html;

    location /assets/ {
        try_files $uri =404;
    }

    location /api/ {
        proxy_pass https://server:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
		try_files $uri /index.html;
	}
}